### ISSUE TITLE
[Operations] Create operations API

### ISSUE THREAD

**Issue by Themimitoof** [Themimitoof/netwark#19]
Create the API routes for : 
 * listing all operations
 * returning all informations about the specified operation
 * create a new operation

## GET: `/api/v1/operations`
Querystring:
 * `per_page`: limit elements per page (default: 50)
 * `page`: page number
 * `status`: filter by operation status
 * `type`: filter by operation type

Return:
```json
[
    {
        "id": "7e81e673-9b64-42ad-ba3f-5e2a74fe9ec7",
        "type": "mtr",
        "target": "1.1.1.1",
        "queues": [
            "lc_paris_eqx_dc2",
            "lc_paris_ild_pa2",
            "lc_ams_eqx_am3"
        ],
        "status": "progress",
        "created_at": "2019-05-01 23:42:23.324324"
    },
   ...
]
```

## GET: `/api/v1/operations/{operation_id}`
Return:
_WIP_

## POST: `/api/v1/operations`
Params:
 * `type`: type of the operation (one of: `OPERATION_FLAGS`)
 * `target`: IP/hostname
 * `options` (optional): options to send to the operation
 * `queues` (optional): list of queues the task will be sent 

Return:
```json
{
  "message": "Request created",
  "resource": "{uuid}"
}
```

Return codes:
 - `200`: OK
 - `400`: Bad request
 - `500`: Internal Error

## Tasks
- [x] Create `collection_get` route
  - [x] Create the pagination system
  - [x] Create the filtering system
- [x] Create `get` route
- [x] Create `post` route
